### ISSUE TITLE
aarch64 Linux support

### ISSUE THREAD

**Issue by psftw** [haskell/docker-haskell#1]
*Note: the original GitHub repository was deleted recently, so we've lost all the issues/discussion* :cry:

We should support an aarch64 variant in addition to x86_64 as soon as it is feasible.

ARM support has been improving in upstream GHC, and with 8.8.1 there are now binaries being published, even though they are not officially supported. I ran in to problems bootstrapping Cabal, and noticed other issues in the [GHC issue tracker](https://gitlab.haskell.org/ghc/ghc/issues?label_name%5B%5D=ARM) which makes an 8.8.1 docker image difficult to put together at this time.

**Comment by akhilgupta74** [comment]
Hey Guys,
Too bad that the original repository was deleted. Missed a lot of my issues as well 😞 

Is there any plan to support aarch64 in Haskell docker?
I can see that GHC has started official support for aarch64 in 8.8.1 but they haven't released official executable package yet at their website (to be fetched by Haskell Dockerfile).

I was working in this direction earlier too & still eagerly waiting for this.
In addition, I have aarch64 machines with me and would be happy to do all kind of experimentation stuff (when required).

Let me know your take on this

**Comment by ossdev07** [comment]
> _Note: the original GitHub repository was deleted recently, so we've lost all the issues/discussion_ 
> 
> We should support an aarch64 variant in addition to x86_64 as soon as it is feasible.
> 
> ARM support has been improving in upstream GHC, and with 8.8.1 there are now binaries being published, even though they are not officially supported. I ran in to problems bootstrapping Cabal, and noticed other issues in the [GHC issue tracker](https://gitlab.haskell.org/ghc/ghc/issues?label_name%5B%5D=ARM) which makes an 8.8.1 docker image difficult to put together at this time.

@psftw @skynet4ps 
I checked latest code and it has support of AARCH64 and according to that i modified dockerfile to run on AARCH64 and it is working fine . Because AARCH64 bin is not released so i added the code in dockerfile to build  locally to use.
i can share my modified dockerfile if you people are interested ..

**Comment by rhenwood-arm** [comment]
@ossdev07 : Having a docker file to start with would be a good start so please share the modified docker file.

@psftw : I guess in order to investigate Cabel, installing Cabel and then installing something like Warp would be a good first data point. Does that sound useful?

**Comment by ossdev07** [comment]
Hi All,
Kindly refer attached modified dockerfile of haskell package with ARM64 support.
[Dockerfile.txt](https://github.com/haskell/docker-haskell/files/4102489/Dockerfile.txt)

**Comment by ossdev07** [comment]
Hi All 

Kindly refer attached modified dockerfile of haskell package using version-8.8.2 with ARM64 support. I have already tested in our system, it is working fine.
[Dockerfile.txt](https://github.com/haskell/docker-haskell/files/4230264/Dockerfile.txt)

**Comment by AlistairB** [comment]
Hi, initial support has been released.

I'm going to track this in #25 , but if anyone following this can try it out it would be greatly appreciated. Note stack does not support aarch64 at least reliably, so is not included. Cheers
