### ISSUE TITLE
Add image for GHC 9.6

### ISSUE THREAD

**Issue by tarleb** [haskell/docker-haskell#102]
GHC 9.6.1 was released on Mar 10: https://www.haskell.org/ghc/download_ghc_9_6_1.html

**Comment by tarleb** [comment]
It seems that upstream does currently not provide a aarch64 linux version of cabal-install 3.10.1.0.

**Comment by tarleb** [comment]
@AlistairB what is the usual way to proceed here? Is this something that we need to act on, or should we just wait for all necessary binaries to become available?

**Comment by AlistairB** [comment]
Ah good pickup. This looks to be an oversight in their release process. Ideally it would be good to [raise an issue](https://github.com/haskell/cabal/issues) to let the cabal folk know it is missing and wait for it to be added. (I was also hoping for aarch64 + deb11 [release](https://github.com/haskell/cabal/issues/8376), although looks like [ghc 9.6.1](https://downloads.haskell.org/~ghc/9.6.1/) does not include aarch64 + deb11 either so still blocked on that front. Looks like [GHC will have this as of 9.8.1](https://gitlab.haskell.org/ghc/ghc/-/issues/22005)).

Another tip, it can be useful to see what ghcup is doing. In this [case](https://github.com/haskell/ghcup-metadata/blob/develop/ghcup-0.0.7.yaml#L3685) we can see that it is using 'unofficial bindists', so ghcup is filling in this blank itself (just to sanity check there is not some other bindist we are not noticing). The docker official images cannot use unofficial releases though.

Also, with 9.6.1 being released, I think it is time to drop 9.0 support. 9.0 was a 'tick' or 'non-LTS' release. See https://github.com/haskellfoundation/tech-proposals/pull/34 (which was not endorsed, but it is still the unofficial policy). With 9.2 being a LTS type release that has a stackage lts and also ghcup has as the 'recommended' version, 9.0 can go I reckon.

**Comment by develop7** [comment]
Fixed by #109
