### ISSUE TITLE
9.4.5 doesn't include the correct GHC

### ISSUE THREAD

**Issue by dtaskoff** [haskell/docker-haskell#108]
Running `stack build` with the following stack.yaml:
```yaml
resolver: lts-21.0
```
downloads `ghc-tinfo6-libc6-pre232-9.4.5`, instead of using the one built into the container.

**Comment by AlistairB** [comment]
Hi, stack is [configured to globally use the pre installed GHC](https://github.com/haskell/docker-haskell/blob/master/9.4/slim-buster/Dockerfile#L53-L54). However, when you use stack in a project by default it will not. I do not think this default is configurable.

If you add:

```yaml
system-ghc: true
install-ghc: false
```

to your stack.yaml it should use the GHC installed into the image.

**Comment by AlistairB** [comment]
Optimistically closing for now. Let us if you think this project still has an issue.
