### ISSUE TITLE
Update official 9.8 images

### ISSUE THREAD

**Issue by DuncanvR** [haskell/docker-haskell#117]
The images haven't been updated following the latest PR. Running e.g. `podman run --rm -it docker.io/haskell:9 cabal --version` returns `cabal-install version 3.8.1.0`, which #114 upgraded to 3.10.2.

If I understand [the instructions in the README](https://github.com/haskell/docker-haskell#2-release-new-versions) correctly, lines [7](https://github.com/docker-library/official-images/blob/master/library/haskell#L7) and [12](https://github.com/docker-library/official-images/blob/master/library/haskell#L12) of the official library definition need to be updated, as they still point to commit 30f9d37 from last September:
```diff
-GitCommit: 30f9d37242fd2ab6a8cf23e546a26b56a0d2636c
+GitCommit: 3d23b935d1de92b907c24b3183a0ee8cdeb459cf
```

I'm don't expect the docker-library repo to accept contributions from strangers, so I thought I'd post here first. The `9.4` tag has been updated following #115, so it looks like only the last PR was skipped.

**Comment by develop7** [comment]
Thank you for the heads-up, bumped official-images with https://github.com/docker-library/official-images/pull/16003
