### ISSUE TITLE
"RUN cabal install --only-dependencies -j4" fails with "Could not find module: <lib_module> with any suffix"

### ISSUE THREAD

**Issue by runeksvendsen** [haskell/docker-haskell#26]
In the **How to use this image** section [here](https://hub.docker.com/_/haskell), the following Dockerfile is given as an example:

```
FROM haskell:8

WORKDIR /opt/example

RUN cabal update

COPY ./example.cabal /opt/example/example.cabal

RUN cabal install --only-dependencies -j4

COPY . /opt/example
RUN cabal install

CMD ["example"]
```

However, when I try to build this image and it reaches the command `RUN cabal install --only-dependencies -j4` cabal fails with an error saying "Could not find module: **x** with any suffix", where **x** is the first module listed in my cabal file under `library -> exposed-modules`.

So it looks like Cabal needs the source code files of my project to be present when running `--only-dependencies` and I don't understand why.

For reference, I'm using the `haskell:8.8.4-buster` image.

**Comment by bubba** [comment]
Using `RUN cabal build --only-dependencies -j4` worked around this for me

**Comment by runeksvendsen** [comment]
Thank you @bubba. I can confirm that this works for me as well.

**Comment by AlistairB** [comment]
Should be fixed in the docs now.
