### ISSUE TITLE
locale setting incorrect

### ISSUE THREAD

**Issue by soiamsoNG** [haskell/docker-haskell#29]
`locale -a`
return
```
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_COLLATE to default locale: No such file or directory
C
C.UTF-8
POSIX
```
affect hGet hPut like function

locale should set to C.UTF-8, to avoid fallback to ASCII since locale setting incorrect

**Comment by psftw** [comment]
Thank you for reporting. While I can't reproduce the error output lines from calling `locale -a` in the images, I agree we should be using C.UTF-8 as a default. I think we can just bake LANG=C.UTF-8 into the image (as was the case < GHC 8.6). Will post a PR later today to address.

**Comment by soiamsoNG** [comment]
> Thank you for reporting. While I can't reproduce the error output lines from calling `locale -a` in the images, I agree we should be using C.UTF-8 as a default. I think we can just bake LANG=C.UTF-8 into the image (as was the case < GHC 8.6). Will post a PR later today to address.

I run under **podman**

**Comment by soiamsoNG** [comment]
> > Thank you for reporting. While I can't reproduce the error output lines from calling `locale -a` in the images, I agree we should be using C.UTF-8 as a default. I think we can just bake LANG=C.UTF-8 into the image (as was the case < GHC 8.6). Will post a PR later today to address.
> 
> I run under **podman**

**Comment by psftw** [comment]
Also came across this great post about the topic https://serokell.io/blog/haskell-with-utf8
