### ISSUE TITLE
Looking for Maintainers

### ISSUE THREAD

**Issue by psftw** [haskell/docker-haskell#5]
*Note: the original GitHub repository was deleted recently, so we've lost all the issues/discussion* :cry:

This project has become a bit neglected over the years. I've responded to issues and kept the release train rolling, though sometimes it can take a few extra weeks to catch up. I'm seeking a motivated Haskell enthusiast to take over and steer the ship more proactively.

Interested? Check out the open issues and read up on the [Official Images process](https://github.com/docker-library/official-images). An ideal candidate is connected to one or more upstream projects or uses Haskell at their job and has a long term interest in supporting this Docker image for the community.

**Comment by hvr** [comment]
I happen to use this docker images myself and I also been maintaining the debian packages this docker image has been feeding off; so I'm happy to (co-)maintain this. I don't want to be the sole maintainer though.

**Comment by phadej** [comment]
I could co-maintain as well.

I have been maintaining

- https://github.com/phadej/docker-ghc
- https://github.com/haskell-CI/haskell-ci/tree/master/docker

image collections, so I might or might not know what I'm doing :)

**Comment by phadej** [comment]
Also I have been wondering, and cannot find an answer in official images process; is there some guidelines what distribution these should be based off? Debian stable (or oldstable), ubuntu LTS? or could one have all variations if there's energy to maintain them? 

Relatedly: https://github.com/haskell-CI/haskell-ci/issues/287

**Comment by psftw** [comment]
Thank you @hvr and @phadej :joy:
Feel free to ping me on freenode anytime. I've just pressed the buttons to give you both the proper GitHub access, though I'd like to still review all changes before merge for now. Add yourselves to https://github.com/docker-library/official-images/blob/master/library/haskell when you have a moment.

@phadej correct, there are no barriers beyond the effort to support extra variants. We've had requests for alpine, centos, and debian:buster in the past, but nobody has jumped in to do the work and take ownership.

Keeping this issue open until we have a brave soul that wants to take over, but I'm already feeling much better about the current state. :100:

**Comment by WillSewell** [comment]
Is this issue resolved then?

**Comment by hvr** [comment]
> Add yourselves to https://github.com/docker-library/official-images/blob/master/library/haskell when you have a moment.

I just realised, I forgot about that detail....

**Comment by psftw** [comment]
Welcome aboard "officially" @hvr :rocket: and thanks again for all the work you do to make this possible!
