### ISSUE TITLE
haskell:run image

### ISSUE THREAD

**Issue by AlistairB** [haskell/docker-haskell#56]
I think it would be nice to have images like `haskell:run-9.2.1-buster` which has the core packages required to run a haskell binary compiled with a given version + platform.

Something like:

```Dockerfile
FROM debian:buster-slim

RUN apt-get update \
 && apt-get install -y --no-install-recommends \
    libgmp10 \
    ca-certificates \
 && rm -rf /var/lib/apt/lists/*
```

**Comment by jmtd** [comment]
`libgmp10` is already installed in `debian:10-slim` and `debian:11-slim`. `ca-certificates` is not. I expect a lot of Haskell programs would need that, but not all: I have been experimenting with builder/runner images for [my thing](https://github.com/striot/striot) and I don't need `ca-certificates` (although I do have other dependencies I do need, so I will still need to do custom runtime images even if you provided some).

Given your resource issues (#72), I would suggest not increasing the burden of the number of images to maintain.

**Comment by AlistairB** [comment]
Ah good point, I did not realise `libgmp10` was bundled with debian these days. In that case I tend to agree the run image desirability goes down a lot. Thanks for the info!
