### ISSUE TITLE
arm64 does not include stack

### ISSUE THREAD

**Issue by AlistairB** [haskell/docker-haskell#59]
Stack has had patchy support of arm64 in the past, [but it is not officially supported](https://github.com/commercialhaskell/stack/issues/2103).

The last released binary is for stack 2.7.1, however I get [this failure on debian buster](https://github.com/commercialhaskell/stack/issues/2103#issuecomment-972329065).

There are unofficial binaries that ghcup uses, but I don't think official images should include anything unofficial.

**Comment by vic1707** [comment]
> Stack has had patchy support of arm64 in the past, [but it is not officially supported](https://github.com/commercialhaskell/stack/issues/2103).
> 
> The last released binary is for stack 2.7.1, however I get [this failure on debian buster](https://github.com/commercialhaskell/stack/issues/2103#issuecomment-972329065).
> 
> There are unofficial binaries that ghcup uses, but I don't think official images should include anything unofficial.

I have the same problem, did you find a workaround? Maybe another image that works with both ARM64 and AMD64?

**Comment by AlistairB** [comment]
I think the only workaround currently is to use an image based on ghcup, as ghcup includes unofficial ARM64 binaries for stack that I assume work.

I have poked the stack folk about fixing ARM64 support and there was no some interest, but not movement as of yet.

**Comment by sanderjo** [comment]
Same here on my ARM / aarch64:

```
sander@nanopineo2:~$ docker run -it haskell:latest /bin/bash
root@04f4e5aea8f2:/# uname -a
Linux 04f4e5aea8f2 5.10.60-sunxi64 #21.08.1 SMP Wed Aug 25 18:29:57 UTC 2021 aarch64 GNU/Linux
root@04f4e5aea8f2:/# stack
bash: stack: command not found
root@04f4e5aea8f2:/#
```
A solution would be nice.

**Comment by AlistairB** [comment]
Unfortunately this will need to be [fixed upstream](https://github.com/commercialhaskell/stack/issues/2103).

The only work around for now is to use the ghcup unofficial binaries. You can install ghcup in a docker image and install stack this way. Unofficial binaries are not appropriate for official docker images though so can't take that approach here.

**Comment by AlistairB** [comment]
Stack is producing aarch64 binaries again, but they still [do not work on debian buster](https://github.com/commercialhaskell/stack/issues/5871).

**Comment by AlistairB** [comment]
This has been resolved

**Comment by benz0li** [comment]
@AlistairB FYI https://github.com/commercialhaskell/stack/issues/6142
