### ISSUE TITLE
Upgrade to debian buster

### ISSUE THREAD

**Issue by Elewyth** [haskell/docker-haskell#8]
Request to upgrade the base-image from `debian:stretch` to `debian:buster` as the current stable release of debian. Maybe provide e.g. `haskell:8.6.5-buster` as to not break any existing tags and switch to buster as the default base-image when a new version of the haskell image (i.e. ghc) is released?

**Comment by phadej** [comment]
Blocked on https://github.com/haskell-CI/haskell-ci/issues/287

**Comment by hvr** [comment]
@phadej we can proceed now!

**Comment by psftw** [comment]
Closing as we are in the process of shipping this, pending upstream Official Images team review at https://github.com/docker-library/official-images/pull/7971
