### ISSUE TITLE
Install `-prof` packages?

### ISSUE THREAD

**Issue by phadej** [haskell/docker-haskell#9]
It would make sense to have them in full images, but omit from `-slim` images.

I just run into a use case where I need `-prof` stuff.

opinions, @hvr @psftw?

**Comment by psftw** [comment]
Sounds reasonable, though if `-prof` is significantly bigger, it may make more sense to add a variant instead? I think we are stuck with quite large images due to GHC + dependencies, so the value of a `-slim` is questionable to me, but I have not looked at the numbers recently.

**Comment by phadej** [comment]
- Rust has e.g. `1-slim-stretch` tag, which downloaded a layer of size 371.3MB for me.
    - their `slim` vs `stretch` differ mainly in the choice of base image.
- Haskell `8.4.4` main layer is is 244MB,

I think we can afford `-prof` in normal image and `-slim` can stay slim. That would be good for consistency with other official images. Our current image is what other call "slim": no extras.

**Comment by AlistairB** [comment]
I'm planning to implement this suggestion. I have seen people expect it recently and I think that is fairly reasonable. So..

- Defaults will include profiling
- Add `-slim` variants (for Debian only) which do not include profiling support and are based off of the debian `-slim` variants.
- Alpine + Windows will also include profiling (when they are supported). I do not think I will add a slim variant here.

The profiling files take the image from 1.73GB -> 2.46GB (600mb) for 9.2 on Debian buster. Not the worst. I think minimising image size is overrated.

**Comment by AlistairB** [comment]
Decided to just pull the trigger as described above.
